# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Muss < Formula
  desc ""
  homepage ""
  version "0.9"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/djbender/muss/releases/download/v0.9/muss_0.9_Darwin_x86_64.tar.gz"
      sha256 "1c7786ad737e23eace04269d318e60ac4fd1d8acc7b445b901c57b01e387cea1"
    end
    if Hardware::CPU.arm?
      url "https://github.com/djbender/muss/releases/download/v0.9/muss_0.9_Darwin_arm64.tar.gz"
      sha256 "579b599c18afbc66646dfb13412a660509c421910071527f5f798b92bc531fce"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/djbender/muss/releases/download/v0.9/muss_0.9_Linux_x86_64.tar.gz"
      sha256 "290bf514283f40ce713299676a8a1527c0ab8e84535491b3858db3453948ed90"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/djbender/muss/releases/download/v0.9/muss_0.9_Linux_arm64.tar.gz"
      sha256 "e40d42d7ad150fb4893b8c3b6c54794bdecbf746a381ecb167b2b9343fd59893"
    end
  end

  depends_on "vault"

  def install
    make "install"
  end

  test do
    system bin/"muss", "help"
  end
end
