# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Muss < Formula
  desc ""
  homepage ""
  version "0.9"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/djbender/muss/releases/download/v0.9/muss_0.9_Darwin_x86_64.tar.gz"
      sha256 "031d1bd724114a91d8382cd688b4b3c27d32171549509b5646af9fbc01668525"
    end
    if Hardware::CPU.arm?
      url "https://github.com/djbender/muss/releases/download/v0.9/muss_0.9_Darwin_arm64.tar.gz"
      sha256 "a9adc7958665303aff705a0db0b528b839e2535c0b8d749442365f42b411be0e"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/djbender/muss/releases/download/v0.9/muss_0.9_Linux_x86_64.tar.gz"
      sha256 "8da45e356bc44918fdbec84a16bc0c52387f7d9dd09362cfd84a181864d7b9dc"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/djbender/muss/releases/download/v0.9/muss_0.9_Linux_arm64.tar.gz"
      sha256 "56f98c968908abc4c90b5de7ac55fad7b0100c502be4f4eed294a436b529e7b5"
    end
  end

  depends_on "vault"

  def install
    make install
  end

  test do
    system bin/"muss", "help"
  end
end
